name: Build
on:
  pull_request:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v1

      - name: Install .NET Core SDK 3.1.101
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.101'

      - name: Run Cake script
        uses: ecampidoglio/cake-action@v1.1.0
